import {request} from './transport.js';
import {setupEditor} from './editor.js';
import {point,pixel} from './model.mjs';
const $=s=>document.querySelector(s),canvas=$('#screen'),ctx=canvas.getContext('2d');
let ui,board,generation=-1,last=0,pressed=false,hash='',buildPending=false;
const log=message=>{const li=document.createElement('li'),time=document.createElement('time');time.textContent=new Date().toLocaleTimeString();li.append(time,document.createTextNode(message));$('#events').prepend(li);while($('#events').children.length>80)$('#events').lastChild.remove();};
function syncTheme(){const index=ui._operit_lvgl_theme_index(),t=board.themes[index];$('#theme').value=index;$('#shape').value=ui._operit_lvgl_round_icons()?'circle':'square';$('#swatches').replaceChildren(...['bg','surface','accent','muted'].map(key=>{const s=document.createElement('span');s.style.background=t[key];return s;}));}
function controls(){ui._operit_lvgl_set_connection($('#wifi').checked,$('#edge').checked);ui.ccall('operit_lvgl_set_expression',null,['string'],[$('#expression').value]);}
function frame(now){if(ui&&now-last>=1000/Number($('#fps').value)){last=now;const before=performance.now();ui._operit_lvgl_pump(0);const next=ui._simulator_generation();if(next!==generation){generation=next;const data=ctx.createImageData(320,240),ptr=ui._simulator_frame(),view=new Uint16Array(ui.HEAPU8.buffer,ptr,320*240);for(let i=0;i<view.length;i++){const v=view[i],r=Math.round((v>>11)*255/31),g=Math.round(((v>>5)&63)*255/63),b=Math.round((v&31)*255/31),rgb=$('#color').value==='rgb332'?pixel(r,g,b,'rgb332'):[r,g,b];data.data.set([...rgb,255],i*4);}ctx.putImageData(data,0,0);}syncTheme();$('#page').textContent=ui.ccall('operit_lvgl_current_page','string',[],[]);$('#render-time').textContent=(performance.now()-before).toFixed(1)+' ms · LVGL '+Math.round(ui._simulator_heap_used()/1024)+' KiB';}requestAnimationFrame(frame);}
function touch(e,down){if(!ui)return;const p=point(e.clientX,e.clientY,canvas.getBoundingClientRect());$('#coords').textContent=p.x+', '+p.y;ui._simulator_touch(p.x,p.y,down?1:0);}
canvas.onpointerdown=e=>{pressed=true;canvas.focus();if(e.isTrusted)canvas.setPointerCapture(e.pointerId);touch(e,true);log('touch down');};canvas.onpointermove=e=>touch(e,pressed);canvas.onpointerup=e=>{pressed=false;touch(e,false);log('touch up');};canvas.onpointercancel=e=>{pressed=false;touch(e,false);};
function home(){if(window.operitEditor){window.dispatchEvent(new CustomEvent('operit-navigate-page',{detail:'home'}));return;}window.dispatchEvent(new Event('operit-runtime-navigation'));ui?._operit_lvgl_navigate_home();$('#page').textContent='Home';}function apps(){if(window.operitEditor){window.dispatchEvent(new CustomEvent('operit-navigate-page',{detail:'apps'}));return;}window.dispatchEvent(new Event('operit-runtime-navigation'));ui?._operit_lvgl_navigate_apps();$('#page').textContent='Apps';}
canvas.onkeydown=e=>{if(window.operitEditor?.isEditing())return;if(['ArrowRight','ArrowLeft','Escape'].includes(e.key)){e.preventDefault();e.key==='ArrowRight'?apps():home();}};
$('#home').onclick=home;$('#apps').onclick=apps;$('#theme').onchange=()=>{window.dispatchEvent(new Event('operit-runtime-navigation'));ui?._operit_lvgl_set_theme(Number($('#theme').value),$('#shape').value==='circle');};$('#shape').onchange=$('#theme').onchange;
for(const id of ['wifi','edge','expression'])$('#'+id).onchange=()=>{if(ui)controls();};
$('#show-grid').onchange=e=>$('#grid').style.display=e.target.checked?'block':'none';$('#clear-log').onclick=()=>$('#events').replaceChildren();$('#color').onchange=()=>generation=-1;$('#reset').onclick=()=>location.reload();$('#capture').onclick=()=>{const a=document.createElement('a');a.download='operit-lvgl-320x240.png';a.href=canvas.toDataURL();a.click();};
async function status(){try{const s=await request('/api/build');$('#build-status').textContent=s.running?'正在构建 WebAssembly + ESP32…':s.error?'构建失败：'+s.error:s.stale?'底层运行时源码已变化，需要开发者构建':s.manifest?.firmwareBuilt?'基础运行时 '+s.manifest.sourceHash.slice(0,12):'预览已构建；固件未验证';buildPending=s.running;if(hash&&s.manifest?.sourceHash&&s.manifest.sourceHash!==hash&&!s.running&&!s.error&&!window.operitEditor?.isDirty()&&!window.operitEditor?.isBusy())location.reload();}catch(e){$('#build-status').textContent=e.message;}}
try{board=await request('/api/board');$('#theme').replaceChildren(...board.themes.map((t,i)=>new Option(t.name,i)));const manifest=await(await fetch('./generated/manifest.json')).json();hash=manifest.sourceHash;const {default:create}=await import('./generated/ui.mjs?v='+hash);ui=await create();ui.onAction=value=>{if(value.startsWith('navigate:')){setTimeout(()=>window.dispatchEvent(new CustomEvent('operit-navigate-page',{detail:value.slice(9)})),0);return;}log('LVGL action: '+value);$('#page').textContent=value;if(value==='face_online'||value==='run_node'){ $('#expression').value=value==='run_node'?'listening':'online';controls();}};if(!ui._simulator_init())throw new Error('LVGL 初始化失败');controls();syncTheme();$('#source').textContent='共用源码：'+manifest.source+' / LVGL '+manifest.lvgl;log('真实 LVGL WebAssembly 已启动');await setupEditor(ui,log);requestAnimationFrame(frame);}catch(e){log('ERROR '+e.message);$('.hint').textContent='预览尚未构建或加载失败，请查看构建状态：'+e.message;$('#editor-status').textContent='加载失败：'+e.message;}
status();setInterval(status,2000);
